import { useEffect, useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useApi } from '../hooks/useApi';
import { PhotoGallery, PhotoRecord } from '../components/PhotoGallery';
import { Sparkles, RefreshCw } from 'lucide-react';

export default function GalleryPage() {
  const router = useRouter();
  const { view } = router.query;
  const { fetchGallery, triggerPrint, triggerUpscale } = useApi();

  const [photos, setPhotos] = useState<PhotoRecord[]>([]);
  const [loading, setLoading] = useState<boolean>(true);

  const loadGallery = async () => {
    setLoading(true);
    try {
      const data = await fetchGallery();
      setPhotos(data);
    } catch (err) {
      console.error("Failed to load gallery:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadGallery();
  }, [fetchGallery]);

  // Handle auto-focus modal if "view" query param exists
  const getSelectedPhotoForQuery = (): PhotoRecord[] => {
    if (!view || photos.length === 0) return photos;
    
    // Check if the queried photo ID exists in the fetched list
    const found = photos.find(p => p.id === view);
    if (found) return photos;

    // If it's not found in the initial page list (e.g. cached or further down), 
    // we can request/query it or temporarily fetch details.
    // For simplicity, we just return the full list.
    return photos;
  };

  return (
    <>
      <Head>
        <title>Public Gallery | AI Anime Portrait Studio</title>
        <meta name="description" content="View beautiful anime portraits generated by visitors at the AI Anime Portrait Studio." />
      </Head>

      <div className="flex flex-col gap-8 w-full">
        
        {/* Header */}
        <div className="flex items-center justify-between border-b border-white/5 pb-4">
          <div>
            <h1 className="text-2xl md:text-3xl font-extrabold tracking-widest text-white font-orbitron">
              COMMUNITY PORTRAITS
            </h1>
            <p className="text-xs text-gray-500 font-sans mt-1">
              Browse artwork created by booth users worldwide.
            </p>
          </div>
          
          <button
            onClick={loadGallery}
            className="p-2.5 rounded-lg border border-white/5 hover:border-cyber-neonBlue bg-cyber-card text-gray-400 hover:text-cyber-neonBlue transition-all"
            title="Refresh Grid"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          </button>
        </div>

        {/* Gallery Grid */}
        {loading ? (
          <div className="flex flex-col items-center justify-center py-24">
            <RefreshCw className="w-10 h-10 text-cyber-neonPurple animate-spin mb-3" />
            <p className="font-orbitron text-xs text-cyber-neonPurple tracking-widest animate-pulse">
              LOADING PORTRAIT GRID...
            </p>
          </div>
        ) : (
          <PhotoGallery
            photos={getSelectedPhotoForQuery()}
            onPrint={triggerPrint}
            triggerUpscale={triggerUpscale}
          />
        )}

      </div>
    </>
  );
}
